language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel

    - os: osx
      r: devel

r_packages:
- fGarch
- landpred
- Matrix
- Rcpp
- RcppArmadillo
- testthat

r_build_args: "--html"

r_check_args: "--as-cran --timings"