language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    
    - os: linux
      dist: trusty
      r: devel
      
  allow_failures:
    - os: osx
      r: release
      
    - os: osx
      r: devel

r_packages:
- fastICA
- fBasics
- fGarch
- landpred
- Matrix
- Rcpp
- RcppArmadillo
- testthat
- covr

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_build_args: "--html"

r_check_args: "--as-cran --timings"