language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel

    - os: osx
      r: release

r_packages:
- fGarch
- landpred
- Matrix
- Rcpp
- RcppArmadillo
- testthat

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_build_args: "--html"

r_check_args: "--as-cran --timings"