language: R
cache: packages
sudo: required

r: 
- release
- devel

os:
- linux
- osx

r_packages:
- fGarch
- landpred
- Matrix
- Rcpp
- RcppArmadillo

r_build_args: "--html"

r_check_args: "--as-cran --timings"